import {test} from 'node:test';import assert from 'node:assert/strict';import {authRequest,authPublic} from '../auth.ts';
function fixture(){const records=new Map<string,any>();const ctx={storage:{async get(k:string){return structuredClone(records.get(k));},async put(k:string,v:any){records.set(k,structuredClone(v));},async delete(k:string){return records.delete(k);},async getAlarm(){return 1;},async setAlarm(){}}} as any;const env={GAME_ROOM:{idFromName:(s:string)=>s,get:()=>({fetch:async()=>Response.json({ok:true})})},RESEND_API_KEY:'test-only',MAIL_FROM:'game@example.test'} as any;return {records,ctx,env,async call(route:string,data:any){const r=await authRequest(ctx,env,new Request('https://auth/'+route,{method:'POST',body:JSON.stringify({ip:route,origin:'https://game.example',...data})}));return {status:r.status,data:await r.json() as any};}};}
test('verification and password reset links expire, are single-use and revoke old sessions',async()=>{const f=fixture(),fetchBefore=globalThis.fetch;let link='';globalThis.fetch=async(_input,init)=>{link=JSON.parse(String(init?.body)).text.match(/https:\/\/game.example\/#[^\n]+/)[0];return Response.json({id:'mail'});};try{
 const reg=await f.call('register',{username:'mail_user',password:'long original password',email:'a@example.test'});assert.equal(reg.status,200);const token=reg.data.token;
 let secret=new URLSearchParams(link.split('#')[1]).get('token');assert.equal((await f.call('verify',{secret})).status,200);assert.equal((await f.call('verify',{secret})).status,400);
 await f.call('forgot',{username:'mail_user'});secret=new URLSearchParams(link.split('#')[1]).get('token');const reset=await f.call('reset',{secret,password:'long replaced password'});assert.equal(reset.status,200);assert.equal((await f.call('session',{token})).data.user,null);assert.equal((await f.call('reset',{secret,password:'long replaced password'})).status,400);
 for(const [key,value] of f.records)if(key.startsWith('mail:'))value.expires=0;
 assert.equal((await f.call('reset',{secret,password:'long replaced password'})).status,400);
}finally{globalThis.fetch=fetchBefore;}});
test('Google uses PKCE and verified provider subject; callback state is checked',async()=>{const f=fixture();f.env.GOOGLE_CLIENT_ID='test';f.env.GOOGLE_CLIENT_SECRET='test-secret';const original=globalThis.fetch;globalThis.fetch=async(input,init)=>{if(String(input).includes('/token')){assert.ok(new URLSearchParams(String(init?.body)).get('code_verifier'));return Response.json({access_token:'provider-token'});}return Response.json({sub:'google-subject',email:'a@example.test',email_verified:true,name:'Google Player'});};try{
 const start=await f.call('google-start',{});assert.equal(start.data.challenge.length,43);
 const done=await f.call('google-finish',{state:start.data.state,code:'valid'});assert.equal(done.status,200);assert.equal(done.data.user.google,true);
 assert.equal((await f.call('google-finish',{state:start.data.state,code:'valid'})).status,400);
 const bad=await authPublic(new Request('https://game.example/api/auth/google/callback?state=forged&code=x'),f.env);assert.equal(bad.status,400);
}finally{globalThis.fetch=original;}});
