import {test} from 'node:test';import assert from 'node:assert/strict';
import {act,addPlayer,freshGame,tick,publicGame,netWorth,finishCheck,scoreTournament,hasWon} from '../game.ts';
import {gameProperties} from '../custom.ts';import {PROPERTIES,BOARD} from '../rules.ts';
function lobby(n=2){const g=freshGame('V5TEST01');for(let i=0;i<n;i++)addPlayer(g,String(i),`P${i}`);return g;}
function start(g:ReturnType<typeof lobby>){for(const p of g.players)act(g,p.id,{type:'ready',ready:true},1000);act(g,'0',{type:'start'},1000,()=>0);return g;}
function playing(n=2){return start(lobby(n))}
test('exact world and Dortmund presets, six groups of three, 32 tiles',()=>{const g=lobby();const world=Object.values(gameProperties(g)).filter(p=>p.kind==='city');assert.equal(world.length,18);assert.equal(BOARD.length,32);assert.equal(new Set(world.map(p=>p.group)).size,6);for(const group of new Set(world.map(p=>p.group)))assert.equal(world.filter(p=>p.group===group).length,3);assert.deepEqual(world.map(p=>p.name),['Dortmund','Hamburg','Berlin','Lyon','Marseille','Paris','Neapel','Mailand','Rom','Chicago','Los Angeles','New York','Osaka','Kyoto','Tokyo','Kutaisi','Batumi','Tiflis']);act(g,'0',{type:'settings',settings:{...g.settings,boardVariant:'dortmund'}});assert.deepEqual(Object.values(gameProperties(g)).filter(p=>p.kind==='city').map(p=>p.name),['Mengede','Nette','Westerfilde','Huckarde','Kirchlinde','Deusen','Eving','Lindenhorst','Brechten','Lütgendortmund','Marten','Bövinghausen','Brackel','Wambel','Asseln','Brückstraße','Nordstadt','Hannibal']);assert.equal(PROPERTIES.dortmund.name,'Dortmund');});
test('team membership and start require 2v2, transfer respects teammate and funds',()=>{const h=lobby();h.settings.teams=true;assert.throws(()=>start(h),/vier/);const g=lobby(4);g.settings.teams=true;start(g);act(g,'0',{type:'team_transfer',toId:'2',amount:100},2000);assert.equal(g.players[0].money,1400);assert.equal(g.players[2].money,1600);assert.throws(()=>act(g,'0',{type:'team_transfer',toId:'1',amount:1},2000));assert.throws(()=>act(g,'0',{type:'team_transfer',toId:'2',amount:2000},2000));g.players[1].bankrupt=true;g.players[3].bankrupt=true;finishCheck(g);assert.equal(g.phase,'finished');assert.equal(g.players.find(p=>p.id===g.winnerId)?.team,0);assert.equal(hasWon(g,'2'),true);assert.equal(hasWon(g,'1'),false);});
test('team wealth sums both teammates for victory',()=>{const g=playing(4);g.settings.teams=true;g.settings.targetWealth=5000;g.players[0].money=2600;g.players[2].money=2600;finishCheck(g);assert.equal(g.winnerId,'0');});
test('missions are private, reward only once and cannot be set by a player action',()=>{const g=lobby();g.settings.missions=true;start(g);assert.ok(publicGame(g,'0').players[0].mission);assert.equal(publicGame(g,'0').players[1].mission,undefined);assert.equal(publicGame(g).players[0].mission,undefined);g.players[0].purchases=3;act(g,'0',{type:'chat',text:'ready'},2000);assert.equal(g.players[0].money,1600);act(g,'0',{type:'chat',text:'again'},2000);assert.equal(g.players[0].money,1600);assert.throws(()=>act(g,'0',{type:'mission',done:true}));});
test('custom start bonus, building costs, auction duration and casino cap are server rules',()=>{const g=lobby();act(g,'0',{type:'settings',settings:{...g.settings,startBonus:500,buildPercent:50,auctionSeconds:60,casinoLimit:2}});start(g);assert.equal(gameProperties(g).dortmund.buildCost,25);g.players[0].position=31;act(g,'0',{type:'roll'},2000,()=>0);assert.ok(g.players[0].money>=2000);g.turnPhase='end';g.actionNotBefore=0;for(let i=0;i<2;i++)act(g,'0',{type:'roulette',bet:1,choice:'red'},6000,()=>0);assert.throws(()=>act(g,'0',{type:'roulette',bet:1,choice:'red'},6000),/Maximal/);g.cities.dortmund.ownerId='0';act(g,'0',{type:'auction_create',cityId:'dortmund',minimum:10},6000);assert.equal(g.auction?.endsAt,66000);});
test('package auction transfers all properties once and blocks invalid bundles',()=>{const g=playing();g.turnPhase='end';g.cities.dortmund.ownerId='0';g.cities.koeln.ownerId='0';assert.throws(()=>act(g,'0',{type:'auction_create',cityIds:['dortmund','tokyo'],minimum:10},2000));act(g,'0',{type:'auction_create',cityIds:['dortmund','koeln'],minimum:100},2000);act(g,'1',{type:'bid',amount:100},3000);tick(g,22001);assert.equal(g.cities.dortmund.ownerId,'1');assert.equal(g.cities.koeln.ownerId,'1');assert.equal(g.players[0].money,1600);assert.equal(g.players[1].money,1400);assert.equal(g.players[1].purchases,2);});
test('replacement vote requires delay and unanimity, active players cannot be taken over',()=>{const g=playing(3);assert.throws(()=>act(g,'0',{type:'replace_bot',playerId:'2'},70000));g.players[2].connected=false;g.players[2].disconnectedAt=1000;assert.throws(()=>act(g,'0',{type:'replace_bot',playerId:'2'},2000));act(g,'0',{type:'replace_bot',playerId:'2'},61001);assert.equal(g.players[2].isBot,false);act(g,'1',{type:'replace_bot',playerId:'2'},61001);assert.equal(g.players[2].replacementBot,true);});
test('trading phase freezes normal actions then resumes and pauses safely',()=>{const g=playing();g.settings.tradingSeconds=30;g.currentPlayerIndex=1;g.turnPhase='end';act(g,'1',{type:'end'},2000,()=>0);assert.equal(g.tradeUntil,32000);const deadline=g.turnDeadline;assert.throws(()=>act(g,'0',{type:'roll'},3000),/Handelsphase/);act(g,'0',{type:'trade',toId:'1',offerCities:[],requestCities:[],offerMoney:10,requestMoney:0},3000);assert.equal(g.trades.length,1);tick(g,31999);assert.equal(g.rollId,0);tick(g,32000);assert.equal(g.tradeUntil,undefined);assert.equal(g.turnDeadline,deadline);act(g,'0',{type:'roll'},32000,()=>0);assert.equal(g.rollId,1);});
test('tournament is scored once and carries points, teams and board into rematch',()=>{const g=playing();g.settings.tournamentGames=3;g.settings.boardVariant='dortmund';g.phase='finished';g.winnerId='0';scoreTournament(g);scoreTournament(g);assert.equal(g.tournament?.played,1);assert.equal(g.tournament?.points['0'],3);act(g,'0',{type:'rematch'});assert.equal(g.tournament?.played,1);assert.equal(g.settings.boardVariant,'dortmund');assert.equal(g.phase,'lobby');});
test('replay contains bounded chronological events and no secrets',()=>{const g=playing();for(let i=0;i<200;i++)act(g,'0',{type:'chat',text:String(i)});act(g,'0',{type:'roll'},2000,()=>0);const last=g.replay!.at(-1)!;assert.equal(last.positions['0'],2);assert.ok(g.replay!.length<=180);assert.ok(!JSON.stringify(g.replay).includes('mission'));assert.equal(netWorth(g,g.players[0]),1500);});

test('consecutive settings patches preserve unrelated host choices',()=>{const g=lobby();act(g,'0',{type:'settings_patch',settings:{missions:true}});act(g,'0',{type:'settings_patch',settings:{boardVariant:'dortmund'}});assert.equal(g.settings.missions,true);assert.equal(g.settings.boardVariant,'dortmund');assert.throws(()=>act(g,'1',{type:'settings_patch',settings:{teams:true}}));});
