// Geographic data for the user's original 18 cities. All game values live in rules.ts.
export interface CityGeo {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  lat: number;
  lon: number;
}
export const CITIES: Record<string, CityGeo> = {
  london: {
    id: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 51.5074,
    lon: -0.1278,
  },
  paris: {
    id: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    lat: 48.8566,
    lon: 2.3522,
  },
  hamburg: {
    id: "hamburg",
    name: "Hamburg",
    country: "Germany",
    countryCode: "DE",
    lat: 53.5511,
    lon: 9.9937,
  },
  berlin: {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    lat: 52.52,
    lon: 13.405,
  },
  dortmund: {
    id: "dortmund",
    name: "Dortmund",
    country: "Germany",
    countryCode: "DE",
    lat: 51.5136,
    lon: 7.4653,
  },
  koeln: {
    id: "koeln",
    name: "Köln",
    country: "Germany",
    countryCode: "DE",
    lat: 50.9375,
    lon: 6.9603,
  },
  duesseldorf: {
    id: "duesseldorf",
    name: "Düsseldorf",
    country: "Germany",
    countryCode: "DE",
    lat: 51.2277,
    lon: 6.7735,
  },
  muenchen: {
    id: "muenchen",
    name: "München",
    country: "Germany",
    countryCode: "DE",
    lat: 48.1351,
    lon: 11.582,
  },
  newyork: {
    id: "newyork",
    name: "New York",
    country: "USA",
    countryCode: "US",
    lat: 40.7128,
    lon: -74.006,
  },
  chicago: {
    id: "chicago",
    name: "Chicago",
    country: "USA",
    countryCode: "US",
    lat: 41.8781,
    lon: -87.6298,
  },
  losangeles: {
    id: "losangeles",
    name: "Los Angeles",
    country: "USA",
    countryCode: "US",
    lat: 34.0522,
    lon: -118.2437,
  },
  miami: {
    id: "miami",
    name: "Miami",
    country: "USA",
    countryCode: "US",
    lat: 25.7617,
    lon: -80.1918,
  },
  saopaulo: {
    id: "saopaulo",
    name: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    lat: -23.5505,
    lon: -46.6333,
  },
  buenosaires: {
    id: "buenosaires",
    name: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    lat: -34.6037,
    lon: -58.3816,
  },
  tokyo: {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    lat: 35.6762,
    lon: 139.6503,
  },
  osaka: {
    id: "osaka",
    name: "Osaka",
    country: "Japan",
    countryCode: "JP",
    lat: 34.6937,
    lon: 135.5023,
  },
  kyoto: {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    lat: 35.0116,
    lon: 135.7681,
  },
  sydney: {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    lat: -33.8688,
    lon: 151.2093,
  },
};
