import {useEffect,useState} from 'react';
import {BOARD,boardPoint,money} from './rules.ts';
import {gameProperties} from './custom.ts';
import type {GameState,Action,Settings} from './game.ts';
import {music, musicIsPlaying, effectsVolume} from './sound.ts';
type Props={game:GameState;you:string;send:(a:Action)=>void};
export function AdvancedLobby({game,you,send}:Props){
 const host=game.players.find(p=>p.id===you)?.isHost;
 const set=(x:Partial<Settings>)=>send({type:'settings_patch',settings:x});
 return <section className="upgrade-panel"><h3>Dein Brett. Deine Spielweise.</h3><div className="preset-picker">{[['world','Welt','6 Länder · 18 Städte'],['dortmund','Dortmund','Mengede bis Hannibal']].map(([id,name,sub])=><button key={id} className={`button ${(game.settings.boardVariant||'world')===id?'gold':''}`} disabled={!host} onClick={()=>set({boardVariant:id as 'world'|'dortmund'})}><b>{name}</b><small>{sub}</small></button>)}</div><details><summary>Alle Orte dieses Bretts</summary><p>{Object.values(gameProperties(game)).filter(p=>p.kind==='city').map(p=>p.name).join(' · ')}</p></details><div className="advanced-settings"><label><input type="checkbox" disabled={!host} checked={!!game.settings.teams} onChange={e=>set({teams:e.target.checked})}/> Teammodus 2 gegen 2</label><label><input type="checkbox" disabled={!host} checked={!!game.settings.missions} onChange={e=>set({missions:e.target.checked})}/> Geheime Missionen (+100 €)</label><label>Turnier<select disabled={!host} value={game.settings.tournamentGames||0} onChange={e=>set({tournamentGames:+e.target.value})}>{[[0,'Einzelpartie'],[3,'3 Partien'],[5,'5 Partien']].map(([n,label])=><option key={n} value={n}>{label}</option>)}</select></label><label>Handelsphase pro Runde<select disabled={!host} value={game.settings.tradingSeconds||0} onChange={e=>set({tradingSeconds:+e.target.value})}><option value={0}>Aus</option><option value={30}>30 Sekunden</option><option value={60}>60 Sekunden</option><option value={120}>120 Sekunden</option></select></label>{([{key:'startBonus',title:'Startbonus',values:[0,100,200,300,500],initial:200,suffix:' €'},{key:'auctionSeconds',title:'Auktionsdauer',values:[10,20,30,60,120],initial:20,suffix:' Sekunden'},{key:'buildPercent',title:'Baukosten',values:[50,75,100,150,200],initial:100,suffix:' %'},{key:'casinoLimit',title:'Casino-Spiele je Zug',values:[0,2,4,6,10,20],initial:4,suffix:''}] as const).map(f=><label key={f.key}>{f.title}<select disabled={!host} value={game.settings[f.key]??f.initial} onChange={e=>set({[f.key]:+e.target.value})}>{f.values.map(n=><option key={n} value={n}>{n}{f.suffix}</option>)}</select></label>)}</div>{game.settings.teams&&<><p>Zwei Spieler je Team. Keine Miete unter Teamkollegen. Grundstücke und Gebäude bleiben einzeln verwaltet; Teamtransfers sind außerhalb von Auktionen, Schulden und Blackjack möglich. Das letzte aktive Team gewinnt. Bei Rundenlimit oder Vermögensziel zählt das Teamvermögen.</p>{game.players.map(p=><label key={p.id} className="team-row">{p.name}<select disabled={!host} value={p.team??0} onChange={e=>send({type:'team_set',playerId:p.id,team:+e.target.value})}><option value={0}>Team Gold</option><option value={1}>Team Türkis</option></select></label>)}</>}</section>;
}
export function Tournament({game}:{game:GameState}){
 if(!game.settings.tournamentGames)return null;const score=game.tournament||{played:0,points:{}};
 return <section className="upgrade-panel"><h3>{score.played>=game.settings.tournamentGames?'Turnier beendet':'Turnierwertung'} · {score.played}/{game.settings.tournamentGames}</h3><small>{game.settings.teams?'Sieg: 3 Punkte für beide Teammitglieder.':'Platz 1: 3 Punkte · Platz 2: 2 · Platz 3: 1.'} Bei Punktgleichheit geteilter Platz.</small>{[...game.players].sort((a,b)=>(score.points[b.id]||0)-(score.points[a.id]||0)).map(p=><p key={p.id}>{p.avatar} {p.name}: <b>{score.points[p.id]||0} Punkte</b>{game.settings.teams?` · Team ${(p.team||0)+1}`:''}</p>)}</section>;
}
export function RoundExtras({game,you,send,now}:Props&{now:number}){
 const p=game.players.find(p=>p.id===you),[amount,setAmount]=useState(100);if(!p)return null;
 const mate=game.settings.teams?game.players.find(x=>x.id!==you&&!x.bankrupt&&x.team===p.team):null;
 return <>{game.tradeUntil&&game.tradeUntil>now&&<div className="status-banner"><b>Gemeinsame Handelsphase · {Math.ceil((game.tradeUntil-now)/1000)} s</b><span>Handel im Handy öffnen. Der Zugtimer pausiert.</span></div>}{p.mission&&<details className="mission-card"><summary>Deine geheime Mission {p.mission.done?'✓ erledigt':''}</summary><p>{p.mission.kind==='purchases'?`Kaufe ${p.mission.target} Grundstücke`:p.mission.kind==='rent'?`Erhalte ${money(p.mission.target)} Miete`:`Schließe ${p.mission.target} Handel ab`} · Belohnung: 100 €</p></details>}{mate&&<details className="upgrade-panel"><summary>Teamtransfer an {mate.name}</summary><label>Betrag<input type="number" min={1} max={p.money} value={amount} onChange={e=>setAmount(+e.target.value)}/></label><button className="button" disabled={!!game.manualPause||p.bankrupt||!Number.isSafeInteger(amount)||amount<1||amount>p.money} onClick={()=>send({type:'team_transfer',toId:mate.id,amount})}>Spielgeld übertragen</button></details>}{game.players.filter(x=>!x.connected&&!x.isBot&&!x.bankrupt).map(x=><div className="status-banner" key={x.id}><span>{x.name} ist getrennt. {Math.max(0,60-Math.floor((now-(x.disconnectedAt||now))/1000))} s bis Bot-Abstimmung.</span><button className="button" disabled={p.bankrupt||!x.disconnectedAt||now-x.disconnectedAt<60000} onClick={()=>send({type:'replace_bot',playerId:x.id})}>Für Bot-Ersatz stimmen ({game.botVotes?.[x.id]?.length||0})</button></div>)}</>;
}
export function Replay({game}:{game:GameState}){
 const [step,setStep]=useState(0),[play,setPlay]=useState(false);const events=game.replay||[],item=events[Math.min(step,events.length-1)];
 useEffect(()=>{if(!play)return;const t=setInterval(()=>setStep(n=>{if(n>=events.length-1){setPlay(false);return n;}return n+1}),1200);return()=>clearInterval(t)},[play,events.length]);
 if(!item)return null;
 return <details className="upgrade-panel replay-panel"><summary>Partie nachspielen · letzte {events.length} Ereignisse</summary><div className="replay-board" role="img" aria-label="Spielpositionen zum ausgewählten Ereignis">{BOARD.map((t,i)=>{const {row,col}=boardPoint(i);return <span key={t.id} style={{gridRow:row+1,gridColumn:col+1}}>{i}</span>})}{game.players.map(p=>{const pos=item.positions[p.id];if(pos===undefined)return null;const {row,col}=boardPoint(pos);return <b key={p.id} title={p.name} style={{gridRow:row+1,gridColumn:col+1,color:p.color,zIndex:2}}>{p.avatar}</b>})}<strong className="replay-center">Runde {item.round}<br/>{item.dice?item.dice.join(' + '):'Spielbeginn'}</strong></div><p aria-live="polite">{item.text}</p><input aria-label="Zeitpunkt der Wiederholung" type="range" min={0} max={events.length-1} value={Math.min(step,events.length-1)} onChange={e=>{setStep(+e.target.value);setPlay(false)}}/><div className="lobby-actions"><button className="button" disabled={step===0} onClick={()=>setStep(n=>Math.max(0,n-1))}>Zurück</button><button className="button" onClick={()=>{if(step>=events.length-1)setStep(0);setPlay(!play)}}>{play?'Anhalten':'Abspielen'}</button><button className="button" disabled={step>=events.length-1} onClick={()=>setStep(n=>Math.min(events.length-1,n+1))}>Weiter</button></div><small>Ereignis {step+1}/{events.length}. Zeigt den Ereignisverlauf und damalige Figurenpositionen; keine Videoaufnahme.</small></details>;
}
type InstallEvent=Event&{prompt:()=>Promise<void>};
export function InstallApp(){const [event,setEvent]=useState<InstallEvent|null>(null),[help,setHelp]=useState(false);useEffect(()=>{const handler=(e:Event)=>{e.preventDefault();setEvent(e as InstallEvent)};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler)},[]);return <div className="install-app"><button className="button" onClick={async()=>{if(event){await event.prompt();setEvent(null)}else setHelp(!help)}}>Als App installieren</button>{help&&<p>Auf dem iPhone: in Safari öffnen → Teilen → Zum Home-Bildschirm. In anderen Browsern die Funktion „App installieren“ im Menü wählen. Online-Partien benötigen Internet.</p>}</div>}
export function AudioSettings(){const [fx,setFx]=useState(()=>Number(localStorage.getItem('we-fx-volume')??.6)),[bg,setBg]=useState(()=>Number(localStorage.getItem('we-music-volume')??.15)),[enabled,setEnabled]=useState(musicIsPlaying);return <section className="upgrade-panel"><h3>Atmosphäre</h3><label>Effekte: {Math.round(fx*100)} %<input type="range" min={0} max={1} step={.05} value={fx} onChange={e=>{const n=+e.target.value;setFx(n);effectsVolume(n)}}/></label><label>Musik: {Math.round(bg*100)} %<input type="range" min={0} max={1} step={.05} value={bg} onChange={e=>{const n=+e.target.value;setBg(n);localStorage.setItem('we-music-volume',String(n));if(enabled)music(true,n)}}/></label><button className="button" onClick={()=>{music(!enabled,bg);setEnabled(!enabled)}}>{enabled?'Musik ausschalten':'Hintergrundmusik starten'}</button><small>Musik startet nur nach deinem Klick. Effekte können zusätzlich über das Lautsprechersymbol stummgeschaltet werden.</small></section>}
