import {useEffect,useState} from 'react';
export type Credential={id:string;key:string};
export function credentials():Credential|null{try{const c=JSON.parse(localStorage.getItem('we-profile')||'null');return c&&/^[A-F0-9]{12}$/.test(c.id)&&/^[a-f0-9]{64}$/.test(c.key)?c:null;}catch{return null;}}
type User={id:string;username:string;email:string;emailVerified:boolean;google:boolean;hasPassword:boolean};
type View={id:string;name:string;avatar?:string;friends:Record<string,string>;invites:{from:string;name:string;room:string}[];stats:{games:number;wins:number;bestWealth:number}};
export function ProfilePanel({room}:{room?:string}){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<View|null>(null),[legacy,setLegacy]=useState(credentials),[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[currentPassword,setCurrent]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState(''),[friend,setFriend]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[config,setConfig]=useState({google:false,email:false}),[secret,setSecret]=useState(''),[legacyCode,setLegacyCode]=useState('');
 async function request(path:string,body?:unknown){const r=await fetch(path,body===undefined?{credentials:'same-origin'}:{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Anfrage fehlgeschlagen.');return d;}
 async function readProfile(id:string,key?:string){const d=await request('/api/profile/'+id,{action:'read',key});setProfile(d);setName(d.name);return d;}
 async function refresh(){const d=await request('/api/auth/session');setUser(d.user);if(d.user){setEmail(d.user.email||'');await readProfile(d.user.id);}else if(legacy)await readProfile(legacy.id,legacy.key);}
 useEffect(()=>{void request('/api/auth/config').then(setConfig).catch(()=>{});void refresh().catch(()=>{});const h=new URLSearchParams(location.hash.slice(1));if(['verify','reset'].includes(h.get('account')||'')){setMode(h.get('account')!);setSecret(h.get('token')||'');history.replaceState(null,'',location.pathname+location.search);}else if(h.get('account')==='welcome'){setMessage('Mit Google angemeldet.');history.replaceState(null,'',location.pathname+location.search);}},[]);
 async function perform(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function submit(){await perform(async()=>{
  if(['register','reset','password'].includes(mode)&&password!==repeat)throw Error('Die Passwörter stimmen nicht überein.');
  const d=await request('/api/auth/'+mode,{username,password,currentPassword,email,secret,legacy:mode==='register'?legacy:undefined});
  setPassword('');setRepeat('');setCurrent('');if(d.user){localStorage.removeItem('we-profile');setLegacy(null);setUser(d.user);await readProfile(d.user.id);window.dispatchEvent(new Event('we-auth-changed'));}
  setMessage(d.notice||(mode==='login'?'Du bist angemeldet.':'Gespeichert.'));if(mode==='verify')setMode('login');if(mode==='reset'||mode==='password')setMode('login');
 });}
 async function profileAction(action:string,extra:Record<string,unknown>={}){await perform(async()=>{const id=user?.id||legacy?.id;if(!id)return;setProfile(await request('/api/profile/'+id,{action,key:legacy?.key,...extra}));if(action==='invite')setMessage('Einladung gesendet.');});}
 const accountForm=!user||['password','email','reset','verify'].includes(mode);
 return <details className="upgrade-panel profile-panel account-panel" open={secret?true:undefined} onToggle={e=>{if(e.currentTarget.open&&!busy)void refresh().catch(()=>{});}}><summary>Konto & Freunde</summary>
 {!user&&<p>Spiele sofort als Gast oder sichere dein Online-Profil mit einem Konto.</p>}
 {legacy&&!user&&<p className="account-notice">Dein bisheriges Profil wird bei der Registrierung übernommen – Freunde und Online-Statistik bleiben erhalten.</p>}
 {accountForm&&<form onSubmit={e=>{e.preventDefault();void submit();}}>
 {!user&&!secret&&<div className="account-tabs"><button type="button" className={`button ${mode==='login'?'gold':''}`} onClick={()=>{setMode('login');setMessage('');}}>Anmelden</button><button type="button" className={`button ${mode==='register'?'gold':''}`} onClick={()=>{setMode('register');setMessage('');}}>Registrieren</button></div>}
 {['login','register','forgot'].includes(mode)&&<label>Benutzername<input required autoComplete="username" autoCapitalize="none" spellCheck={false} pattern="[A-Za-z0-9_]{3,20}" minLength={3} maxLength={20} value={username} onChange={e=>setUsername(e.target.value)}/></label>}
 {['password','email'].includes(mode)&&<label>Aktuelles Passwort<input required type="password" autoComplete="current-password" maxLength={128} value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label>}
 {['login','register','reset','password'].includes(mode)&&<label>{mode==='login'?'Passwort':'Neues Passwort · mindestens 12 Zeichen'}<input required type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>}
 {['register','reset','password'].includes(mode)&&<label>Passwort wiederholen<input required type="password" autoComplete="new-password" minLength={12} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>}
 {['register','email'].includes(mode)&&<><label>E-Mail {mode==='register'?'(optional)':''}<input type="email" autoComplete="email" required={mode==='email'} maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><small>Eine bestätigte E-Mail ermöglicht das Zurücksetzen des Passworts.{!config.email?' Der Mailversand ist auf diesem Server noch nicht aktiviert.':''}</small></>}
 {mode==='verify'&&<p>Bestätige deine E-Mail-Adresse für die Kontowiederherstellung.</p>}
 <button className="button gold full" disabled={busy} type="submit">{busy?'Einen Moment …':({login:'Anmelden',register:'Konto erstellen',forgot:'Reset-Link anfordern',reset:'Neues Passwort speichern',verify:'E-Mail bestätigen',password:'Passwort ändern',email:'Bestätigungslink senden'} as Record<string,string>)[mode]}</button>
 {mode==='login'&&<button type="button" className="text-button" onClick={()=>setMode('forgot')}>Passwort vergessen?</button>}
 {user&&<button type="button" className="text-button" onClick={()=>setMode('login')}>Zurück zum Profil</button>}
 </form>}
 {!user&&<><a className={`button full google-login ${!config.google?'unavailable':''}`} href={config.google?'/api/auth/google/start':undefined} aria-disabled={!config.google}>Mit Google anmelden</a>{!config.google&&<small>Google-Anmeldung wird nach der Einrichtung durch den Betreiber verfügbar.</small>}<p className="fineprint">Du kannst ohne Konto weiterspielen. Deine lokale Karriere bleibt auf diesem Gerät.</p><details><summary>Vorhandenen V5-Anmeldecode übernehmen</summary><label>Alter Anmeldecode<input type="password" autoComplete="off" value={legacyCode} onChange={e=>setLegacyCode(e.target.value)}/></label><button className="button" disabled={busy} onClick={()=>perform(async()=>{const [id,key]=legacyCode.trim().split('.');await readProfile(id,key);const c={id,key};localStorage.setItem('we-profile',JSON.stringify(c));setLegacy(c);setLegacyCode('');setMode('register');setMessage('Altes Profil erkannt. Lege jetzt Benutzername und Passwort fest.');})}>Profil übernehmen</button></details></>}
 {user&&<div className="profile-identity"><span className="profile-avatar">{profile?.avatar||'♜'}</span><div><h3>{profile?.name||user.username}</h3><small>@{user.username}</small><p>{user.google?'Google-Konto':user.emailVerified?'E-Mail bestätigt':user.email?'E-Mail noch nicht bestätigt':'Ohne Wiederherstellungs-E-Mail'}</p></div></div>}
 {user&&profile&&<><div className="metric-grid"><div><small>Partien</small><strong>{profile.stats.games}</strong></div><div><small>Siege</small><strong>{profile.stats.wins}</strong></div></div><p>Bestes Vermögen: {profile.stats.bestWealth.toLocaleString('de-DE')} €</p><details><summary>Profil bearbeiten</summary><label>Anzeigename<input maxLength={20} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button" disabled={busy||!name.trim()} onClick={()=>profileAction('rename',{name})}>Name speichern</button><div className="avatar-choices">{['♜','♞','♛','♝','♚','♟'].map(avatar=><button className="button" key={avatar} aria-label={'Profilfigur '+avatar} aria-pressed={(profile.avatar||'♜')===avatar} disabled={busy} onClick={()=>{void profileAction('avatar',{avatar});localStorage.setItem('we-avatar',avatar);}}>{avatar}</button>)}</div>{user.hasPassword&&<><button className="button" onClick={()=>setMode('password')}>Passwort ändern</button><button className="button" onClick={()=>setMode('email')}>E-Mail ändern / bestätigen</button></>}</details>
 <p>Freundescode: <strong>{profile.id}</strong></p><label>Freundescode eingeben<input maxLength={12} autoCapitalize="characters" value={friend} onChange={e=>setFriend(e.target.value.toUpperCase())}/></label><button className="button" disabled={busy||friend.length!==12} onClick={()=>profileAction('friend_add',{friend})}>Freund hinzufügen</button><small>Für Einladungen müsst ihr euch gegenseitig hinzufügen.</small>{Object.entries(profile.friends).map(([id,n])=><div className="friend-row" key={id}><span>{n}</span>{room&&<button className="button" disabled={busy} onClick={()=>profileAction('invite',{friend:id,room})}>Einladen</button>}<button className="text-button" disabled={busy} onClick={()=>profileAction('friend_remove',{friend:id})}>Entfernen</button></div>)}{profile.invites.map(i=><a className="button" key={i.from+i.room} href={`/?room=${i.room}`}>{i.name} · Raum {i.room}</a>)}</>}
 {user&&<button className="text-button" disabled={busy} onClick={()=>perform(async()=>{await request('/api/auth/logout',{});window.dispatchEvent(new Event('we-logout'));setUser(null);setProfile(null);setMode('login');setMessage('Abgemeldet.');})}>Abmelden</button>}
 {message&&<p className="account-message" role="status">{message}</p>}
 </details>;
}
