import {useEffect,useRef} from 'react';
import {debtPlan,groupChanges,propertyColor,sortedProperties,tradeValue} from './advisors.ts';
import {gameProperties} from './custom.ts';
import {groupName} from './presets.ts';
import {money} from './rules.ts';
import {netWorth,rent,type GameState,type Action} from './game.ts';
export function PropertyTags({game,ids}:{game:GameState;ids:string[]}){const props=gameProperties(game);return <span className="property-tags">{sortedProperties(game,ids).map(id=><span className="property-tag" key={id} style={{borderLeftColor:propertyColor(game,id)}}>{props[id].name}{game.cities[id].mortgaged?' · Hypothek':''}</span>)}</span>;}
export function TradeComparison({game,a,b,give,receive,giveMoney,receiveMoney}:{game:GameState;a:string;b:string;give:string[];receive:string[];giveMoney:number;receiveMoney:number}){
 const sent=tradeValue(game,give,giveMoney),got=tradeValue(game,receive,receiveMoney);return <section className="trade-comparison"><h4>Handelsvergleich</h4><div className="metric-grid"><div><small>Du gibst · Buchwert</small><b>{money(sent)}</b></div><div><small>Du erhältst · Buchwert</small><b>{money(got)}</b></div></div><p>Differenz für dich: {got-sent>=0?'+':''}{money(got-sent)}</p>{[{id:a,out:give,inc:receive},{id:b,out:receive,inc:give}].map(side=><div key={side.id}><b>{game.players.find(p=>p.id===side.id)?.name}</b>{groupChanges(game,side.id,side.out,side.inc).map(c=><p key={c.group}>{groupName(game,c.group)}: {c.before}/{c.total} → {c.after}/{c.total}{c.complete?' · Gruppe vollständig':c.lost?' · Vollständige Gruppe wird aufgelöst':` · Noch ${c.total-c.after} fehlen`}</p>)}</div>)}<small>Kaufpreise + Baukosten − Hypothekenwert + Bargeld. Orientierung, kein fairer Marktpreis. Hypotheken bleiben bestehen; bebaute Gruppen sind nicht handelbar.</small></section>;
}
export function DebtHelper({game,you,send,active}:{game:GameState;you:string;send:(a:Action)=>void;active:boolean}){
 if(game.debt?.playerId!==you)return null;const plan=debtPlan(game,you),first=plan.steps[0];return <section className="debt-helper"><h3>Hilfe beim Bezahlen</h3><p>Es fehlen <strong>{money(plan.shortfall)}</strong>.</p>{!plan.shortfall?<p>Du kannst die Rechnung jetzt begleichen.</p>:<><ol>{plan.steps.map((step,i)=><li key={i}>{step.label} <b>+{money(step.gain)}</b></li>)}</ol>{plan.remaining>0?<p>Auch danach fehlen {money(plan.remaining)}. Handel kann helfen; ohne ausreichende Mittel bleibt die Insolvenz.</p>:<p>Mit diesen Schritten kannst du die Rechnung decken.</p>}{first&&<button className="button" disabled={!active} onClick={()=>send(first.action)}>Nächster Schritt: {first.label} · +{money(first.gain)}</button>}<small>Jeder Schritt wird einzeln bestätigt. Verkäufe sind endgültig; verpfändete Grundstücke bringen keine Miete. Der Vorschlag wird nach jeder Aktion neu berechnet.</small></>}</section>;
}
export function OwnershipDialog({game,id,onClose}:{game:GameState;id:string;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);const p=game.players.find(x=>x.id===id);if(!p)return null;const props=gameProperties(game),ids=sortedProperties(game,Object.values(game.cities).filter(c=>c.ownerId===id).map(c=>c.id));return <dialog ref={dialog} className="ownership-dialog" onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose();}} aria-label={`Besitz von ${p.name}`}><header><h2><span style={{color:p.color}}>{p.avatar}</span> {p.name}</h2><button className="button" autoFocus onClick={onClose}>Schließen</button></header><div className="metric-grid"><div><small>Geld</small><b>{money(p.money)}</b></div><div><small>Vermögen</small><b>{money(netWorth(game,p))}</b></div><div><small>Miete erhalten</small><b>{money(p.rentCollected)}</b></div><div><small>Miete gezahlt</small><b>{money(p.rentPaid)}</b></div></div><h3>Grundstücke · {ids.length}</h3>{!ids.length&&<p>Noch keine Grundstücke.</p>}{ids.map(id=>{const c=game.cities[id],d=props[id];return <article className="ownership-property" key={id} style={{borderLeftColor:propertyColor(game,id)}}><b>{d.name}</b><small>{groupName(game,d.group)}</small><span>{c.mortgaged?'Verpfändet':c.developmentLevel===5?'Hotel':`${c.developmentLevel} Häuser`} · Miete {money(rent(game,id))}</span></article>;})}<h3>Aktien</h3>{game.stocks.filter(s=>(p.stocks[s.id]||0)>0).map(s=><p key={s.id}>{s.id.toUpperCase()}: {p.stocks[s.id]} Stück · {money(s.price*p.stocks[s.id])}</p>)}{!game.stocks.some(s=>(p.stocks[s.id]||0)>0)&&<p>Keine Aktien.</p>}</dialog>;
}
